stages:
- name: build&compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.taimei.com/taimei
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
