stages:
- name: 生成jar
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn clean deploy -B -e -U
- name: 登录harbor
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: docker login -u admin -p 123456 harbor.mobilemd.cn
- name: 生成并推送镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello-world-springboot:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.mobilemd.cn
- name: 部署
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
